### ISSUE TITLE
PWM?

### ISSUE THREAD

**Issue by gergoerdi** [Patryk27/avr-tester#2]
Does `avr-tester` provide an PI for testing PWM-driving firmwares? Of course, one way would be to "co-bitbang" (observe bit-by-bit) the output on some PWM pin, but for performance considerations I would hope for something higher-level that would emulate a "DAC", i.e. something that can be queried at a point in the simulation for its frequency and duty cycle. 

The context of this is I would like to interactively and in real time simulate a circuit that does one-bit sound synthesis. If I could get access to the frequency and duty cycle of its PWM-driven pins, I could use that information to synthesize a square wave in the simulation environment. But if I had to run the simulation for one cycle, read the one-bit sound output pin, then run the simulation again for one cycle, etc., then this has no chance of producing enough observations in time to fill my output audio buffer.

**Comment by Patryk27** [comment]
I think that running the simulation for one step and reading the pins in a loop is the only solution there is 🤔 

simavr (which avr-tester uses internally) supports running the simulation for one step only anyway, so even if you do something like `avr.run_for_ms(1);` this is just a shortcut for `avr.run();` (which executes single AVR instruction) repeated multiple times.

**Comment by Patryk27** [comment]
Hi, simulating PWM should be pretty easy with components now - e.g. something like this should simulate a ~50% duty cycle PWM:

```rust
async fn pwm() {
    let avr = avr_rt();

    loop {
        avr.pins().pd0().toggle();
        avr.run().await;
    }
}

#[test]
fn test() {
    /* ... */

    avr.components().add(pwm());
    avr.run_for_us(60);
}
```

Similarly, a ~25% duty cycle PWM could look like:

```rust
async fn pwm() {
    let avr = avr_rt();

    loop {
        avr.pins().pd0().set_high();
        avr.run_for(1); // run for 1 clock cycle

        avr.pins().pd0().set_low();
        avr.run_for(3); // run for 3 clock cycles
    }
}
```

Note that because some AVR instructions (like multiplication) can take more than once cycle, this is only going to approximate given duty cycle - for instance if the simulated program happens to perform a multiplication over the `avr.run_for(1);` instruction, that particular duty cycle will actually be 2/(2+3) = 40% instead of 25%; but unless that program consistently does only multiplication (or other "long" instructions), those small differences should get evened out in the long term and shouldn't make any actual problems with tests.
